repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # ローカル開発では自動整形・修正（commit段階）
      - id: ruff-format
        stages: [pre-commit]
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      # CI/Pushでは検査のみ（fixしない）
      - id: ruff
        name: ruff (check on push)
        stages: [pre-push]

  # mypyはuv環境を利用（追加依存の記述を撤廃）
  - repo: local
    hooks:
      - id: mypy
        name: mypy (uv)
        entry: uv run mypy
        language: system
        pass_filenames: false
        stages: [pre-push]

  # Shell scripts lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: shellcheck (scripts)
        files: ^scripts/(.*\.sh)$
        args: ["--severity=warning", "--external-sources"]

  # 機密検出はpush段階のみ（重さを回避）
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [pre-push]
