#!/usr/bin/env bash
set -euo pipefail

# Local one-time setup helper for MindBridge
# - Creates .env with only required fields
# - Ensures Obsidian vault path exists

cyan="\033[36m"; green="\033[32m"; yellow="\033[33m"; red="\033[31m"; reset="\033[0m"

echo -e "${cyan}MindBridge セットアップ${reset}"

if [[ -f .env ]]; then
  read -r -p "既に .env があります。上書きしますか? [y/N] " yn
  case ${yn:-N} in
    [Yy]*) ;;
    *) echo "キャンセルしました"; exit 0;;
  esac
fi

read -r -p "Discord Bot Token を入力: " DISCORD_BOT_TOKEN
read -r -p "Gemini API Key を入力: " GEMINI_API_KEY

DEFAULT_VAULT="$HOME/Obsidian/MindBridge"
read -r -p "Obsidian Vault パス [${DEFAULT_VAULT}]: " OBSIDIAN_VAULT_PATH
OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH:-$DEFAULT_VAULT}

read -r -p "Discord Guild ID (任意): " DISCORD_GUILD_ID

cat > .env <<EOF
# Generated by scripts/local-setup.sh
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
GEMINI_API_KEY=${GEMINI_API_KEY}
OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH}
DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
ENVIRONMENT=personal
LOG_LEVEL=INFO
EOF

mkdir -p "${OBSIDIAN_VAULT_PATH}"

echo -e "${green}✓ .env を作成しました${reset}"
echo -e "${green}✓ Vault ディレクトリを確認/作成しました: ${OBSIDIAN_VAULT_PATH}${reset}"

echo
echo -e "次のコマンドで起動できます:"
echo -e "  uv sync --dev && uv run python -m src.main"
echo
echo -e "${yellow}オプション:${reset} 音声認識や Garmin を使う場合は .env に追記してください (.env.example 参照)"
